site_name: Security By Reason
theme:
  name: material

nav:
  - Inicio: index.md

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tu-perfil
    - icon: fontawesome/solid/envelope
      link: mailto:info@securitybyreason.org
  # Esta línea es fundamental para que MkDocs no ignore archivos con punto
  copy_dot_files: true

# Esta instrucción obliga a incluir la carpeta .well-known en la compilación
include_dot_files: true
