site_name: Security By Reason
theme:
  name: material

nav:
  - Inicio: index.md

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tu-perfil
    - icon: fontawesome/solid/envelope
      link: mailto:tu-correo@securitybyreason.org

extra_assets:
  - .well-known/security.txt
